#!/bin/bash

echo "Installing XCode"
xcode-select --install

if ! [ -x "$(command -v brew)" ]
then
  echo "Installing Homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew cask &> /dev/null

brew cask install google-chrome
brew cask install 1password
brew cask install atom
brew cask install slack
brew cask install alfred
brew cask install iterm2
brew cask install textexpander
brew cask install banktivity

brew install rbenv

brew install python
brew install python3

pip install virtualenv
pip install virtualenvwrapper

defaults import com.googlecode.iterm2 dotfiles/com.googlecode.iterm2.plist

brew install zsh zsh-completions
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
rm ~/.zshrc
cp dotfiles/zshrc ~/.zshrc
chsh -s /bin/zsh
